// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NapaEduLessons1.Context;

#nullable disable

namespace NapaEduLessons1.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20240127145819_VehiclesMigration")]
    partial class VehiclesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NapaEduLessons1.Models.Passport", b =>
                {
                    b.Property<int>("PassportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassportId"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PassportId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Passport");

                    b.HasData(
                        new
                        {
                            PassportId = 1,
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            PersonId = 2,
                            Series = "AA11111"
                        },
                        new
                        {
                            PassportId = 2,
                            BirthDate = new DateTime(1990, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Doe",
                            PersonId = 1,
                            Series = "BB22222"
                        });
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Age = 43,
                            Name = "Jane"
                        },
                        new
                        {
                            PersonId = 2,
                            Age = 33,
                            Name = "John"
                        });
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Address = "default",
                            BirthDate = new DateTime(2024, 1, 26, 19, 58, 18, 853, DateTimeKind.Local).AddTicks(9901),
                            City = "default",
                            Course = "default",
                            FirstName = "default",
                            LastName = "default"
                        },
                        new
                        {
                            StudentID = 2,
                            Address = "default2",
                            BirthDate = new DateTime(2024, 1, 25, 19, 58, 18, 853, DateTimeKind.Local).AddTicks(9913),
                            City = "default2",
                            Course = "default2",
                            FirstName = "default2",
                            LastName = "default2"
                        });
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("PersonId");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            BrandName = "BMW",
                            ManufacturedDate = new DateTime(2023, 1, 27, 19, 58, 18, 854, DateTimeKind.Local).AddTicks(182),
                            Mileage = 100,
                            Model = "M3",
                            PersonId = 1
                        },
                        new
                        {
                            VehicleId = 2,
                            BrandName = "Audi",
                            ManufacturedDate = new DateTime(2014, 1, 27, 19, 58, 18, 854, DateTimeKind.Local).AddTicks(185),
                            Mileage = 40000,
                            Model = "A6",
                            PersonId = 1
                        },
                        new
                        {
                            VehicleId = 3,
                            BrandName = "Chevrolet",
                            ManufacturedDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 100,
                            Model = "Camaro",
                            PersonId = 2
                        },
                        new
                        {
                            VehicleId = 4,
                            BrandName = "Tesla",
                            ManufacturedDate = new DateTime(2023, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mileage = 180,
                            Model = "Model S",
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Passport", b =>
                {
                    b.HasOne("NapaEduLessons1.Models.Person", "Person")
                        .WithOne("Passport")
                        .HasForeignKey("NapaEduLessons1.Models.Passport", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Vehicle", b =>
                {
                    b.HasOne("NapaEduLessons1.Models.Person", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NapaEduLessons1.Models.Person", b =>
                {
                    b.Navigation("Passport")
                        .IsRequired();

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
